package golang

const (
	goTemplate = `// Code generated by https://github.com/meerkat-lib/disorder; DO NOT EDIT.
package {{PackageName .Package}}
{{- if .ResolvedImports}}

import (
{{- range .ResolvedImports}}
	"{{.}}"
{{- end}}
)
{{- end}}
{{- range $index, $enum := .Enums}}

type {{PascalCase $enum.Name}} string

func ({{PascalCase $enum.Name}}) Enum() {}

const (
{{- range .Values}}
	{{PascalCase $enum.Name}}{{PascalCase .}} {{PascalCase $enum.Name}} = "{{.}}"
{{- end}}
)
{{- end}}
{{- range .Messages}}

type {{PascalCase .Name}} struct {
	{{- range .Fields}}
	{{PascalCase .Name}} {{Type .Type}}` +
		" `disorder:\"{{.Name}}\"`" + `{{- end}}
}
{{- end}}`
)
