package golang

const (
	defineTemplate = `// Code generated by https://github.com/meerkat-io/disorder; DO NOT EDIT.
package {{PackageName .Package}}
{{- if .DefineImports}}

import (
{{- range .DefineImports}}
	"{{.}}"
{{- end}}
)
{{- end}}
{{- range $i, $enum := .Enums}}

type {{PascalCase $enum.Name}} string

const (
{{- range .Values}}
	{{PascalCase $enum.Name}}{{PascalCase .}} = {{PascalCase $enum.Name}}("{{.}}")
{{- end}}
)

var {{CamelCase $enum.Name}}EnumMap = map[string]Color {
{{- range .Values}}
	"{{.}}":{{PascalCase $enum.Name}}{{PascalCase .}},
{{- end}}
}

func (*{{PascalCase $enum.Name}}) Enum() {}

func (enum *{{PascalCase $enum.Name}}) Decode(value string) error {
	if {{CamelCase $enum.Name}}, ok := {{CamelCase $enum.Name}}EnumMap[value]; ok {
		*enum = {{CamelCase $enum.Name}}
		return nil
	}
	return fmt.Errorf("invalid enum value")
}

func (enum *{{PascalCase $enum.Name}}) Encode() ([]byte, error) {
	name := string(*enum)
	if len(name) == 0 {
		return nil, fmt.Errorf("empty enum value")
	}
	if len(name) > 255 {
		return nil, fmt.Errorf("string length overflow. should less than 255")
	}
	data := []byte{byte(len(name))}
	if _, ok := {{CamelCase $enum.Name}}EnumMap[name]; ok {
		data = append(data, []byte(name)...)
		return data, nil
	}
	return nil, fmt.Errorf("invalid enum value")
}
{{- end}}
{{- range .Messages}}

type {{PascalCase .Name}} struct {
	{{- range .Fields}}
	{{PascalCase .Name}} {{Type .Type}} {{Tag .Type .Name}}
	{{- end}}
}
{{- end}}`
)
