package: test

import: 
  - sub_schema.yaml

option:
  go_package_prefix: github.com/meerkat/demo

messages:
  object:
    int_field: int
    string_field: string
    enum_field: color
    int_array: array[int]
    int_map: map[int]
    obj_array: array[sub.sub_object]
    obj_map: map[sub.sub_object]

  another_object:
    value: int

enums:
  color:
    - red
    - green
    - blue

  animal:
    - dog
    - cat

services:
  primary_service:
    get_another_object:
      input: string
      output: another_object

    print_object:
      input: object
      output: null