package: test_data.test

import: 
  - sub_schema.yaml

option:
  go_package_prefix: github.com/meerkat-io/disorder/internal

messages:
  object:
    int_field: int
    string_field: string
    enum_field: color
    int_array: array[int]
    int_map: map[int]
    obj_array: array[test_data.test.sub.sub_object]
    obj_map: map[test_data.test.sub.sub_object]
    time: timestamp
    null_obj: test_data.test.sub.sub_object
    # any_field: any
    # any_array: array[any]
    # any_map: map[any]

enums:
  color:
    - red
    - green
    - blue

services:
  primary_service:
    print_object:
      input: object
      output: object

    print_sub_object:
      input: test_data.test.sub.sub_object
      output: test_data.test.sub.sub_object

    print_time:
      input: timestamp
      output: timestamp

    print_array:
      input: array[int]
      output: array[int]

    print_enum:
      input: color
      output: color

    print_map:
      input: map[string]
      output: map[string]

    # print_any:
      # input: any
      # output: any