package: test_data.test

import: 
  - sub_schema.yaml

option:
  go_package_prefix: github.com/meerkat-io/disorder/internal

messages:
  object:
    int_field: int
    string_field: string
    bytes_fields: bytes
    enum_field: color
    time_field: timestamp
    obj_field: test_data.test.sub.sub_object
    int_array: array[int]
    int_map: map[int]
    obj_array: array[test_data.test.sub.sub_object]
    obj_map: map[test_data.test.sub.sub_object]
    empty_string: string
    empty_enum: color
    empty_time: timestamp
    empty_obj: test_data.test.sub.sub_object
    empty_array: array[int]
    empty_map: map[int]
    nested: map[map[array[array[map[color]]]]]

  zero:
    zero_array: array[int]
    zero_map: map[int]

enums:
  color:
    - red
    - green
    - blue

services:
  primary_service:
    print_object:
      input: object
      output: object

    print_sub_object:
      input: test_data.test.sub.sub_object
      output: test_data.test.sub.sub_object

    print_time:
      input: timestamp
      output: timestamp

    print_array:
      input: array[int]
      output: array[int]

    print_enum:
      input: color
      output: color

    print_map:
      input: map[string]
      output: map[string]

    # print_nested: