package: test_data.test

import: 
  - sub_schema.yaml

option:
  go_package_prefix: github.com/meerkat-io/disorder/internal

messages:
  object:
    int_field: i32
    string_field: string
    enum_field: color
    int_array: array[i32]
    int_map: map[i32]
    obj_array: array[test_data.test.sub.sub_object]
    obj_map: map[test_data.test.sub.sub_object]
    time: timestamp

enums:
  color:
    - red
    - green
    - blue

  animal:
    - dog
    - cat

services:
  primary_service:
    print_object:
      input: object
      output: object

    print_sub_object:
      input: test_data.test.sub.sub_object
      output: test_data.test.sub.sub_object

    print_time:
      input: timestamp
      output: timestamp

    print_array:
      input: array[i32]
      output: array[i32]

    print_enum:
      input: color
      output: color

    print_map:
      input: map[string]
      output: map[string]