package = "test_data.test.sub"

[option]
  go_package_prefix = "github.com/meerkat-io/disorder/internal"

[messages]

[messages.sub_object]
  value = "int"

[services]

[services.math_service]
    
[services.math_service.increase]
  input = "int"
  output = "int"