package = "test_data.test.sub"

[option]
  go_package_prefix = "github.com/meerkat-lib/disorder/internal"

[messages]

[messages.sub_object]
  value = "i32"

[services]

[services.math_service]
    
[services.math_service.increase]
  input = "i32"
  output = "i32"